default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= Rails.application.credentials.dig(:development, :postgres_username) %>
  password: <%= Rails.application.credentials.dig(:development, :postgres_password) %>
  pool: 5

development:
  <<: *default
  database: talk_push_test_app_development


test:
  <<: *default
  database: talk_push_test_app_test
